config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls


urlpatterns = [
    path("", include("home.urls")),
    path('admin/', admin.site.urls),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

app_name = "home"


urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("test/", views.TestView.as_view(), name="test"),
]

templates/base.html
{% load static wagtailcore_tags %}

<!DOCTYPE html>
<html lang="fr-FR">		
    <head>
		<meta charset="UTF-8">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <script src="https://unpkg.com/alpinejs" defer></script>
        <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>
        <script defer type='text/javascript' src="{% static 'js/front.js' %}"></script>
        <script defer src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

        {% block head %}{% endblock head %}
        <link rel="stylesheet" href="{% static 'css/tailwind_output.css' %}">
        <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/collapse@3.14.3/dist/cdn.min.js"></script>
        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.3/dist/cdn.min.js"></script>
        
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

        <!-- TODO UNE FOIS LE SITE EN LIGNE Changer les infos ci-dessous pour le référencement -->
        <link rel="canonical" href="https://www.happy-chocolatine.fr/" />
        <meta property="og:locale" content="fr_FR" />
        <meta property="og:type" content="page" />
        <meta property="og:title" content="Happy Dev toulouse" />
        <meta property="og:description" content="Les meilleurs chocolatiniers du numérique, Lorem ipsum. Lire plus." />
        <meta property="og:url" content="https://www.happy-chocolatine.fr/" />
        <meta property="og:site_name" content="Happy Dev Toulouse" />
        <meta property="article:publisher" content="https://www.facebook.com/happydevnetwork/" />
        <meta property="article:modified_time" content="2024-04-24T08:22:58+00:00" />
        <meta property="og:image" content="{% static 'home/img/logo_HD_toulouse.png' %}" />
        <meta property="og:image:width" content="500" />
        <meta property="og:image:height" content="325" />
        <meta property="og:image:type" content="image/png" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@_Happy_Dev_" />
        <meta name="twitter:label1" content="Durée de lecture estimée" />
        <meta name="twitter:data1" content="2 minutes" />
        <!-- Fin TODO -->
        
    </head>

    <body class="{% block body_class %}{% endblock body_class %}">

        <header class="bg-white shadow-2xl border-b border-gray-50 mb-32">

            <div class="inner_header">

                <a class="home_logo_ink" href="{% url 'home:home' %}">
                    <img class="main_logo" src="{% static '/img/logo_HD_toulouse-bandeau-min.png' %}" />
                </a>
                

                <div id="popout">
                    <nav class="main_nav" role="nav">
                        <ul>
                            <!--<li><a href="{% url 'wagtail_serve' '' %}"><span>Blog</span></a></li>
                            <li><a href="#"><span>Membres</span></a></li>-->
                            <li><a class="contact" data-href="#contact" href="{% url 'home:contact' %}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
    
                <div id="togglemenu" aria-expanded="false" aria-controls="primary-menu">
                    <svg id="burger" xmlns="http://www.w3.org/2000/svg" width="27.285" height="20.255" viewBox="0 0 27.285 20.255">
                        <g transform="translate(-318 -25)">
                            <line x2="24.285" transform="translate(319.5 26.5)" fill="none" stroke="#6760D2" stroke-linecap="round" stroke-width="3"/>
                            <line x2="24.285" transform="translate(319.5 35.127)" fill="none" stroke="#6760D2" stroke-linecap="round" stroke-width="3"/>
                            <line x2="24.285" transform="translate(319.5 43.755)" fill="none" stroke="#6760D2" stroke-linecap="round" stroke-width="3"/>
                        </g>
                    </svg>
                    <svg id="closemenu" xmlns="http://www.w3.org/2000/svg" width="21.415" height="21.415" viewBox="0 0 21.415 21.415">
                        <g transform="translate(-320.935 -23.048)">
                            <g >
                                <line x2="24.285" transform="translate(323.057 25.169) rotate(45)" fill="none" stroke="#FFDE70" stroke-linecap="round" stroke-width="3"/>
                                <line x2="24.285" transform="translate(323.057 42.341) rotate(-45)" fill="none" stroke="#FFDE70" stroke-linecap="round" stroke-width="3"/>
                            </g>
                        </g>
                    </svg>
                </div>

            </div>
            
        </header>

        <main>

            {% block main_title %}{% endblock main_title %}

            {% block content %}{% endblock content %}
        </main>

        <footer>

            <a href="{% url 'home:home' %}">
                <img src="{% static 'img/logo_HD_toulouse_transparent.png' %}">
            </a>

            <div class="footer_nav">

                <a href="#">
                    <span>Mentions légales</span>
                </a>

                &nbsp;|&nbsp;

                <a target="_blank" href="https://www.linkedin.com/company/happydev-toulouse">
                    <span>Suivez-nous 👉</span>&nbsp;
                    <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M24.1429 0H1.85134C0.829911 0 0 0.841518 0 1.87455V24.1254C0 25.1585 0.829911 26 1.85134 26H24.1429C25.1643 26 26 25.1585 26 24.1254V1.87455C26 0.841518 25.1643 0 24.1429 0ZM7.85804 22.2857H4.00446V9.87768H7.86384V22.2857H7.85804ZM5.93125 8.18304C4.69509 8.18304 3.69687 7.17902 3.69687 5.94866C3.69687 4.7183 4.69509 3.71429 5.93125 3.71429C7.16161 3.71429 8.16562 4.7183 8.16562 5.94866C8.16562 7.18482 7.16741 8.18304 5.93125 8.18304ZM22.3031 22.2857H18.4496V16.25C18.4496 14.8107 18.4205 12.9594 16.4473 12.9594C14.4393 12.9594 14.1317 14.5263 14.1317 16.1455V22.2857H10.2781V9.87768H13.975V11.5723H14.0272C14.5437 10.5973 15.8031 9.57009 17.6777 9.57009C21.5777 9.57009 22.3031 12.1411 22.3031 15.4839V22.2857Z" fill="#F2EEE1"/>
                    </svg>
                </a> 

            </div>

        </footer>

    </body>
</html>